---
title: Louise Douet-Sinenberg, Scénographe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    preview: http://placehold.it/300x300
    layout: post
  uploads:
    title: Uploads
    output: true
email: louise.douet.sinenberg@gmail.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://louiseds.github.io
twitter_username: louisedouetsinenberg
github_username: louiseds
markdown: kramdown
permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: 'http://louiseds.github.io/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "preview"
        field:
          element: "text"
          value: "http://placehold.it/300x300"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "text"
          value: CURRENT_DATETIME
