---
title: Louise Douet-Sinenberg, Scénographe
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    preview: http://placehold.it/300x300
    layout: post
  uploads:
    title: Uploads
    output: true
email: louise.douet.sinenberg@gmail.com
description: ''

baseurl: ''
url: http://louiseds.github.io
media: images
markdown: kramdown
permalink: pretty
